M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 12:12:07 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T12:12:07-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.3Y-4.1
X5.4Y-4.2
X5.7Y-4.0
X5.7Y-4.1
X5.8Y-3.7
X5.8Y-3.8
X5.9Y-3.9
X6.0Y-3.7
X6.1Y-3.8
X6.2Y-3.9
X6.2Y-4.0
X6.2Y-4.2
T2
X5.2Y-3.7
X5.4Y-3.7
T0
M30
